name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.10.20'
          
      - name: Run clj-kondo
        run: clj-kondo --lint src test

      - name: Leiningen test
        uses: ./lein/
        with:
          exec: lein test

      - name: Leiningen uberjar
        uses: ./lein/
        with:
          exec: lein uberjar

      - name: Docker build
        run: docker build -t clojure-potato-catalog:cpc-${{ github.run_number }} .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_URL }}
          IMAGE_TAG: ${{ github.run_number }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          docker tag clojure-potato-catalog:cpc-$RUN_NUMBER $ECR_REPOSITORY/clojure-potato-catalog:cpc-$IMAGE_TAG
          docker push $ECR_REPOSITORY/clojure-potato-catalog:cpc-$IMAGE_TAG