name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.10.20'
          
      - name: Run clj-kondo
        run: clj-kondo --lint src test

      - name: Leiningen test
        uses: ./lein/
        with:
          exec: lein test

      - name: Leiningen uberjar
        uses: ./lein/
        with:
          exec: lein uberjar